# Generated by Django 6.0.5 on 2026-05-20 01:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotedecafe',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lotedecafe',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lotedecafe',
            name='preco_saca',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lotedecafe',
            name='qualidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='lotedecafe',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='lotedecafe',
            name='etapa',
            field=models.CharField(choices=[('plantio', 'Plantio'), ('colheita', 'Colheita'), ('secagem', 'Secagem'), ('armazenamento', 'Armazenamento'), ('torra', 'Torra'), ('qualidade', 'Qualidade'), ('venda', 'Venda')], default='plantio', max_length=30),
        ),
    ]
