# Generated by Django 6.0.5 on 2026-05-21 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_lotedecafe_criado_em_lotedecafe_observacoes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('quantidade_sacas', models.IntegerField()),
                ('qualidade', models.CharField(max_length=100)),
                ('preco_saca', models.DecimalField(decimal_places=2, max_digits=10)),
                ('etapa', models.CharField(choices=[('Plantio', 'Plantio'), ('Colheita', 'Colheita'), ('Secagem', 'Secagem'), ('Armazenamento', 'Armazenamento')], max_length=50)),
                ('lavoura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lavoura')),
            ],
        ),
    ]
