# Generated by Django 6.0.5 on 2026-05-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_lote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lote',
        ),
    ]
