# Generated by Django 6.0.5 on 2026-05-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_lote_registrooperacional_lotedecafe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaofinanceira',
            name='tipo',
            field=models.CharField(choices=[('LUCRO', 'Lucro'), ('DESPESA', 'Despesa')], max_length=20),
        ),
    ]
