# Generated by Django 6.0.5 on 2026-05-31 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_movimentacaofinanceira_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrooperacional',
            name='etapa',
            field=models.CharField(default='plantio', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrooperacional',
            name='local',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
