# Generated by Django 6.0.5 on 2026-06-01 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_registrooperacional_etapa_registrooperacional_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionarioPropriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(limit_choices_to={'tipo': 'funcionario'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.propriedade')),
            ],
            options={
                'unique_together': {('funcionario', 'propriedade')},
            },
        ),
    ]
