# Generated by Django 6.0.5 on 2026-06-01 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_funcionariopropriedade'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotedecafe',
            name='responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'funcionario'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_responsaveis', to=settings.AUTH_USER_MODEL),
        ),
    ]
